import React, { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { 
  faLeaf, 
  faChartLine, 
  faShield, 
  faAddressBook, 
  faFlask, 
  faChartBar, 
  faCalculator, 
  faPiggyBank 
} from '@fortawesome/free-solid-svg-icons';
import styled from 'styled-components';

const MenuWrapper = styled.div`
  position: fixed;
  left: ${props => props.isDocked ? '0' : '-250px'};
  top: 0;
  bottom: 0;
  width: 250px;
  background-color: #f8f9fa;
  transition: left 0.3s ease-in-out;
  box-shadow: 2px 0 5px rgba(0, 0, 0, 0.1);
  z-index: 1000;
`;

const MenuToggle = styled.button`
  position: absolute;
  right: -40px;
  top: 10px;
  background: linear-gradient(180deg, #0072ff, #00c6ff);
  color: white;
  border: none;
  padding: 10px;
  cursor: pointer;
  border-radius: 0 5px 5px 0;
  transition: opacity 0.3s;

  &:hover {
    opacity: 0.8;
  }
`;

const MenuList = styled.ul`
  list-style-type: none;
  padding: 0;
  margin: 60px 0 0 0;
`;

const MenuItem = styled.li`
  padding: 15px 20px;
  cursor: pointer;
  transition: all 0.3s;
  display: flex;
  align-items: center;
  position: relative;
  overflow: hidden;

  &:before {
    content: '';
    position: absolute;
    top: 0;
    left: -100%;
    width: 100%;
    height: 100%;
    background: linear-gradient(90deg, #0072ff, #00c6ff);
    transition: left 0.3s ease;
    z-index: -1;
  }

  &:hover {
    color: white;
    
    &:before {
      left: 0;
    }
  }
`;

const MenuIcon = styled(FontAwesomeIcon)`
  margin-right: 10px;
  color: #0072ff;
  transition: transform 0.3s, color 0.3s;

  ${MenuItem}:hover & {
    transform: scale(1.2);
    color: white;
  }
`;

const MenuText = styled.span`
  transition: color 0.3s;
  position: relative;
  z-index: 1;

  ${MenuItem}:hover & {
    color: white;
  }
`;

const MainContent = styled.main`
  margin-left: ${props => props.isDocked ? '250px' : '0'};
  transition: margin-left 0.3s ease-in-out;
`;

const MainMenu = ({ children }) => {
  const [isDocked, setIsDocked] = useState(true);

  const menuItems = [
    { title: 'Production Supply and Demand', icon: faLeaf },
    { title: 'Price and Price Trends', icon: faChartLine },
    { title: 'Product Standards & Consumer Safety', icon: faShield },
    { title: 'Directory and Profiles', icon: faAddressBook },
    { title: 'Research Info and Technology Generated by R&D', icon: faFlask },
    { title: 'Marketing Data and Forecast', icon: faChartBar },
    { title: 'Resource Accounting Data', icon: faCalculator },
    { title: 'Credit Facilities and Programs', icon: faPiggyBank },
  ];

  const toggleMenu = () => {
    setIsDocked(!isDocked);
  };

  return (
    <>
      <MenuWrapper isDocked={isDocked}>
        <MenuToggle onClick={toggleMenu}>
          {isDocked ? '◀' : '▶'}
        </MenuToggle>
        <MenuList>
          {menuItems.map((item, index) => (
            <MenuItem key={index}>
              <MenuIcon icon={item.icon} />
              <MenuText>{item.title}</MenuText>
            </MenuItem>
          ))}
        </MenuList>
      </MenuWrapper>
      <MainContent isDocked={isDocked}>
        {children}
      </MainContent>
    </>
  );
};

export default MainMenu;