import React from 'react'
import { useRef, useEffect, useState } from 'react'   
import videoBG from '../assets/finalvideo.mp4'
import daLogo from "../assets/DA_Logo.png"
import bpLogo from '../assets/Bagong Pilipinas Logo.png'
import { Link } from 'react-router-dom'
import { FaChartLine, FaDollarSign, FaClipboardCheck, FaAddressBook, FaFlask, FaChartBar, FaCalculator, FaCreditCard } from 'react-icons/fa';
import { IoMdMenu } from 'react-icons/io';

const Sidebar = () => {
  const [isOpen, setIsOpen] = useState(false);

  const toggleSidebar = () => {
    setIsOpen(!isOpen);
  };

  const menuItems = [
    { title: 'Production Supply and Demand', icon: <FaChartLine />, link: '/dadospowerbiportal' },
    { title: 'Price and Price Trends', icon: <FaDollarSign />, link: '/price-trends' },
    { title: 'Product Standards & Consumer Safety', icon: <FaClipboardCheck />, link: '/standards-safety' },
    { title: 'Directory & Profiles', icon: <FaAddressBook />, link: '/directory' },
    { title: 'Research Info and Technology Generated by R&D', icon: <FaFlask />, link: '/research' },
    { title: 'Marketing Data & Forecast', icon: <FaChartBar />, link: '/marketing' },
    { title: 'Resource Accounting Data', icon: <FaCalculator />, link: '/accounting' },
    { title: 'Credit Facilities & Programs', icon: <FaCreditCard />, link: '/credit' },
  ];

  return (
    <div className={`sidebar ${isOpen ? 'open' : ''}`}>
      <button className="toggle-btn" onClick={toggleSidebar}>
        <IoMdMenu />
      </button>
      <nav>
        <ul>
          {menuItems.map((item, index) => (
            <li key={index}>
              <Link to={item.link}>
                {item.icon}
                <span>{item.title}</span>
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </div>
  );
};

const Main = () => {
  const videoRef = useRef(null);

  useEffect(() => {
    const handleVideoStart = () => {
      if (videoRef.current) {
        videoRef.current.currentTime = 2;
      }
    };

    const videoElement = videoRef.current;
    if (videoElement) {
      videoElement.addEventListener('loadeddata', handleVideoStart);
    }

    return () => {
      if (videoElement) {
        videoElement.removeEventListener('loadeddata', handleVideoStart);
      }
    };
  }, []);

  return (
    <div className='main'>
      <Sidebar />
      <video ref={videoRef} src={videoBG} autoPlay loop muted />
      <div className='dark-overlay'></div>
      <div className='content'>
        <div className='tataks'>
          <img src={daLogo} alt="D.A Logo" className='tatak' />
          <img src={bpLogo} alt="Bagong Pilipinas Logo" className='tatak' />
        </div>
        <h1>Department of Agriculture</h1>
        <p>Regional Field Office 02</p>
      </div>
    </div>
  );
};

export default Main;